# model
img_res: 224
repr_type: "tan"
resnet_depth: 34
mlp_layers: 1
fourier_block: True
activ_fn: "leaky_relu"

# training
learn_noise: True
loss_name: "chordal"
train_steps: 400000
epochs: 18
batch_size: 16
n_slices: 256
ckpt_steps: 50000

# learning rate
init_lr: 1.0e-4
lr_decay_rate: 0.95
end_lr: 1.0e-5

# EMA (Exponential Moving Average)
ema_enabled: [True]
ema_steps: 5
ema_tau: 0.999

# noise schedule
noise_start: 1.0e-8
noise_end: 1.0
timesteps: 100
power: 3.0
